import Head from "next/head";
import Link from "next/link";

function about() {
  return (
    <>
    <Head>
        <title>ABOUT Tutorial developedbyed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div>about</div>
    <Link href="/">LINK TO HOMEPAGE</Link>
    </>
  )
}

export default about