import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import { useState, useEffect } from 'react';
import useSWR from 'swr';
import Movie from '../components/Movie';


export default function Home() {

const fetcher = (...args) => fetch(...args).then((res) => res.json())
const { data, error } = useSWR(`https://api.themoviedb.org/3/movie/popular?api_key=eb89474ed3551141c9241176893f33ab&language=en-US&page=1`, fetcher)
if (error) return <div>Failed to load</div>
if (!data) return <div>Loading...</div>

console.log(data);

  return (
    <>
      <Head>
        <title>Tutorial developedbyed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className=''>hello nextjs</h1>
        <Link href="/about/about">LINK TO ABOUT</Link>
        <div className='grid gap-16 grid-cols-fluid'>
          {data.results.map((movie) => (
            <Movie
              key={movie.id}
              id={movie.id}
              title={movie.title}
              release_date={movie.release_date}
              poster_path={movie.poster_path}
            />
          ))}
        </div>
      </main>
    </>
  )
}

  /* const [data, setData] = useState(null)
  const [isLoading, setLoading] = useState(false)

  useEffect(() => {
    setLoading(true)
    fetch(`https://api.themoviedb.org/3/movie/popular?api_key=${process.env.API_KEY}&language=en-US&page=1`)
      .then((res) => res.json())
      .then((data) => {
        setData(data)
        setLoading(false)
      })
  }, [])

  if (isLoading) return <p>Loading...</p>
  if (!data) return <p>No profile data</p>

  console.log(data);
  */
